services:
  web:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - go-app
    networks:
      - mynet

  mysql:
    image: mysql/mysql-server:8.0
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - mynet
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s  
      timeout: 5s    
      retries: 10   

  go-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    container_name: go-app
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_NAME: ${DB_NAME}
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mynet

networks:
  mynet:
    driver: bridge

volumes:
  mysql_data:
